/* Renaming COSTOMER Column to Customer */
DATA PROJECT.SPEND;
SET PROJECT.SPEND(rename= (COSTOMER=CUSTOMER));
RUN;


PROC PRINT DATA= PROJECT.REPAYMENT;
RUN;

/*RENAMING column and Dropping null Column & blank rows */
DATA PROJECT.REPAYMENT;
SET PROJECT.REPAYMENT(RENAME=(COSTOMER=CUSTOMER) FIRSTOBS=1 OBS=1500);
DROP E;
RUN;

PROC PRINT DATA=PROJECT.REPAYMENT;
RUN;



/* Replacing Age with the mean age where age<18 */
PROC SQL;
CREATE TABLE AGE_MEAN AS
(SELECT ROUND(AVG(AGE),1) AS MEAN_AGE FROM PROJECT.CUSTOMER);
QUIT;

PROC SQL;
UPDATE PROJECT.CUSTOMER
SET AGE = (SELECT MEAN_AGE FROM AGE_MEAN)
WHERE AGE<18;
QUIT;

PROC PRINT DATA=PROJECT.CUSTOMER;
RUN;


/* Updating Amount>limit with limit/2 */
PROC SQL;
    UPDATE PROJECT.SPEND AS ps
    SET Amount = (
        SELECT CASE WHEN ps.Amount > pc.Limit THEN pc.Limit / 2 ELSE ps.Amount END
        FROM PROJECT.CUSTOMER AS pc
        WHERE ps.CUSTOMER = pc.CUSTOMER
    );
QUIT;

PROC PRINT DATA=PROJECT.SPEND;
RUN;

/* Updating Amount>limit with limit */
PROC SQL;
    UPDATE PROJECT.REPAYMENT AS pr
    SET Amount = (
        SELECT CASE WHEN pr.Amount > pc.Limit THEN pc.Limit ELSE pr.Amount END
        FROM PROJECT.CUSTOMER AS pc
        WHERE pr.CUSTOMER = pc.CUSTOMER
    );
QUIT;

PROC PRINT DATA=PROJECT.REPAYMENT;
RUN;



