/* City in which bank is making the maximum profit */

PROC SQL;
CREATE TABLE PROFITBYCUST AS
SELECT DISTINCT * FROM WORK.MONTHLY_PROFIT;
QUIT;

PROC SQL;
CREATE TABLE PROFITBYCITY AS
SELECT pc.CITY, SUM(MONTHLYPROFIT) AS TOTALPROFIT
FROM PROJECT.CUSTOMER pc INNER JOIN WORK.PROFITBYCUST pbc
on pc.CUSTOMER = pbc.CUSTOMER
GROUP BY pc.CITY
ORDER BY TOTALPROFIT DESC;
QUIT;

PROC PRINT DATA= WORK.PROFITBYCITY;
TITLE "BANK PROFIT BY CITY";
RUN;

PROC SGPLOT DATA=WORK.PROFITBYCITY;
    VBAR CITY / RESPONSE=TOTALPROFIT datalabel;
    TITLE "BANK PROFIT BY CITY";
RUN;
