/* Which age group is spending more money */

PROC SQL;
CREATE TABLE SpendingByAge AS
SELECT
CASE
    WHEN c.Age BETWEEN 18 AND 24 THEN '18-24'
    WHEN c.Age BETWEEN 25 AND 34 THEN '25-34'
    WHEN c.Age BETWEEN 35 AND 44 THEN '35-44'
    WHEN c.Age BETWEEN 45 AND 54 THEN '45-54'
    WHEN c.Age BETWEEN 55 AND 64 THEN '55-64'
    WHEN c.Age >= 65 THEN '65 and above'
    ELSE 'Unknown'
    END AS AgeGroup,
SUM(s.Amount) AS TotalSpending
FROM PROJECT.Customer c
INNER JOIN PROJECT.Spend s
ON c.Customer = s.Customer
GROUP BY AgeGroup
ORDER BY TotalSpending DESC;
QUIT;

PROC PRINT DATA=WORK.SPENDINGBYAGE;
TITLE "SPENDING BY AGE-GROUP";
RUN;

PROC SGPLOT DATA=WORK.SPENDINGBYAGE;
VBAR AGEGROUP / RESPONSE= TOTALSPENDING DATALABEL;
TITLE "SPENDING BY AGE-GROUP";
RUN;


