/* Category in which the customers are spending more money */

PROC SQL;
CREATE TABLE CategorySpending AS
SELECT TYPE, SUM(AMOUNT) AS TOTAL_SPENDING
FROM PROJECT.SPEND
GROUP BY TYPE
ORDER BY TOTAL_SPENDING DESC;
QUIT;


PROC PRINT DATA= WORK.CATEGORYSPENDING;
TITLE "SPENDING CATEGORY WISE";
RUN;

PROC SGPLOT DATA=WORK.CATEGORYSPENDING;
    VBAR TYPE / RESPONSE=TOTAL_SPENDING datalabel;
    TITLE2 "Total Spending by Type";
RUN;