/* Which customer is spending more than limit */

PROC SQL;
CREATE TABLE SPENDLIMIT AS
SELECT CUSTOMER, LIMIT, AMOUNT
FROM PROJECT.CUST_SPEND
WHERE AMOUNT>LIMIT;
QUIT;

PROC SQL;
TITLE "Total Number Of Customers who spend more than the limit";
SELECT COUNT(DISTINCT CUSTOMER) as Count_of_Customers FROM WORK.SPENDLIMIT;
QUIT;


PROC SQL;
TITLE "CUSTOMER SPENDING MORE THAN THE LIMIT AMOUNT";
SELECT DISTINCT CUSTOMER FROM WORK.SPENDLIMIT;
QUIT;